# Generated by Django 5.2.17 on 2026-09-06 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="کد"),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مقدار تخفیف"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "درصدی"), ("fixed", "مبلغ ثابت")],
                        default="percentage",
                        max_length=10,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="حداقل مبلغ خرید",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حداکثر تعداد استفاده"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد استفاده شده"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="تاریخ شروع اعتبار")),
                (
                    "valid_until",
                    models.DateTimeField(verbose_name="تاریخ پایان اعتبار"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "کوپن",
                "verbose_name_plural": "کوپن ها",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["valid_until"], name="shop_coupon_valid_u_c64bfe_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به روز رسانی"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="پرداخت شده"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts",
                        to="shop.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts",
                        to="shop.coupon",
                        verbose_name="کوپن",
                    ),
                ),
            ],
            options={
                "verbose_name": "سبد خرید",
                "verbose_name_plural": "سبد خرید ها",
                "ordering": ("customer", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["customer"], name="shop_cart_custome_86b221_idx"
                    )
                ],
            },
        ),
    ]
