# Generated by Django 5.2.17 on 2026-09-13 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_coupon_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="تعداد",
                    ),
                ),
                ("unit_price", models.PositiveIntegerField(verbose_name="قیمت واحد")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "آیتم سبد خرید",
                "verbose_name_plural": "آیتم های سبد خرید",
                "ordering": ("-created_at",),
            },
        ),
        migrations.RemoveIndex(
            model_name="brand",
            name="shop_brand_name_c466ec_idx",
        ),
        migrations.RemoveIndex(
            model_name="brand",
            name="shop_brand_slug_5e71ec_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="shop_cart_custome_86b221_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="shop_catego_slug_5ac49f_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="shop_catego_parent__bb774a_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="shop_custom_phone_70f608_idx",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "درصدی"), ("fixed", "مبلغ ثابت")],
                default="percentage",
                max_length=20,
                verbose_name="نوع تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="product",
            name="brief_explanation",
            field=models.CharField(
                blank=True, default="", max_length=250, verbose_name="توضیح مختصر"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
                verbose_name="امتیاز محصول از ۰ تا ۵",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shop.cart",
                verbose_name="سبد خریداری",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shop.product",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
